-- 임시환자와 기존 정규환자를 통합할 때 원본 임시환자를 보존하기 위한 컬럼
ALTER TABLE PATIENT ADD (
    MERGED_TO_PATIENT_ID VARCHAR2(36 CHAR),
    MERGED_AT TIMESTAMP
);

ALTER TABLE PATIENT ADD CONSTRAINT FK_PATIENT_MERGED_TO
    FOREIGN KEY (MERGED_TO_PATIENT_ID) REFERENCES PATIENT (PATIENT_ID);

ALTER TABLE PATIENT ADD CONSTRAINT CK_PATIENT_MERGED_NOT_SELF
    CHECK (MERGED_TO_PATIENT_ID IS NULL OR MERGED_TO_PATIENT_ID <> PATIENT_ID);

CREATE INDEX IX_PATIENT_MERGED_TO ON PATIENT (MERGED_TO_PATIENT_ID);
