-- 이름을 알 수 없는 임시환자에게 고유한 숫자 식별자를 부여한다.
ALTER TABLE PATIENT ADD (TEMP_PATIENT_NO NUMBER(12));

CREATE SEQUENCE TEMP_PATIENT_NO_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 50
    NOCYCLE;

-- 이전 임시환자 기본 이름과 난수 접미사 이름은 다시 미확인 상태로 돌린다.
UPDATE PATIENT
SET PATIENT_NAME = NULL
WHERE TEMP_PATIENT_YN = 'Y'
  AND (PATIENT_NAME = '무명환자' OR PATIENT_NAME LIKE '무명환자-%');

-- 기존 이름 미확인 임시환자에게 번호를 한 번씩 발급한다.
UPDATE PATIENT
SET TEMP_PATIENT_NO = TEMP_PATIENT_NO_SEQ.NEXTVAL
WHERE TEMP_PATIENT_YN = 'Y'
  AND PATIENT_NAME IS NULL
  AND TEMP_PATIENT_NO IS NULL;

COMMIT;

ALTER TABLE PATIENT ADD CONSTRAINT UQ_PATIENT_TEMP_PATIENT_NO
    UNIQUE (TEMP_PATIENT_NO);
